### PR TITLE
fix: hash link parser docusaurus version 3

### LINKED ISSUE #214: Search result path not correct
### Please describe the bug you are seeing

Hi,

I installed this plugin to an empty docusaurus project and run all the command without any customization or modifications. When i build and serve the project the search works and shows results fine, but the path where the result is pointing is not working correct.

I dont know if this is a undocumentened config or bug.

Screenshot 2024-07-05 113950

As you can see from the image the path is duplicating after the docs part.

"https://symmetrical-space-doodle-x5rrrgx9pq4hv74v-3000.app.github.dev/docs/tutorial-extras/translate-your-site/docs/tutorial-extras/translate-your-site#start-your-localized-site"

When it should be:

"https://symmetrical-space-doodle-x5rrrgx9pq4hv74v-3000.app.github.dev/docs/tutorial-extras/translate-your-site#start-your-localized-site"

Thanks!

### How can we best reproduce the bug?

1. Install docusaurus
2. Install plugin with default settings
3. Test

### Which version of Docusaurus and @cmfcmf/docusaurus-search-local are you using?

Latest  that are available

### Which Node.js version are you using?

22.3.0

### Which theme are you using?

Yes, I am using @docusaurus/theme-classic

### How does your plugin config look like?

Default config

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by fxamauri**
Resolves #214 issue in docursaurus version 3 where the link hash is not handled correctly. The fix ensures that the hash part of the link is extracted correctly.

related https://github.com/cmfcmf/docusaurus-search-local/pull/204, related https://github.com/cmfcmf/docusaurus-search-local/issues/205

### CODE REVIEW

**Comment by HLeithner** [comment]
Thanks works as expected

File: packages/docusaurus-search-local/src/server/parse.ts [hunk 1]
```diff
@@ -124,8 +124,9 @@ export function html2text(
           // <a class="hash-link" href="#first-header" title="Direct link to heading">#</a>
           .not("a[aria-hidden=true], a.hash-link")
           .text();
-        const hash = $(heading).find("a.hash-link").attr("href") || "";
-
+        const linkHash = $(heading).find("a.hash-link").attr("href") || "";
+        const [, hashPart] = linkHash.split("#");
+        const hash = hashPart ? `#${hashPart}` : "";
```
Comment (slorber) [inline packages/docusaurus-search-local/src/server/parse.ts:129]: Looks better than the code before assuming an anchor never includes a pathname

Please note that an anchor can contain `#` characters 😄 

CleanShot 2024-08-13 at 13 33 24

Comment (fxamauri) [reply packages/docusaurus-search-local/src/server/parse.ts:129]: Good point, @slorber , thx for pointing it out! Didn't think about that. Do you think using new URL().hash could fix it?

**Comment by cmfcmf** [comment]
Thank you!
